# Generated by Django 5.0.1 on 2024-01-26 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товара')),
                ('sellers_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена продавца')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма налога')),
                ('bank_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия за покупку')),
                ('seller_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия за перевод продавцу')),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Комиссия платформы')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Итоговая цена')),
                ('sale', models.BooleanField(default=False, verbose_name='Распродажа')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='Процент скидки')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена на распродаже')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
